### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Song367** [jimmm-ai/TimeUi-a-ComfyUi-Timeline-Node#9]
Traceback (most recent call last):
  File "E:\workplace\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\workplace\\ComfyUI\\custom_nodes\\TimeUi-a-ComfyUi-Timeline-Node\\__init__.py'

Cannot import E:\workplace\ComfyUI\custom_nodes\TimeUi-a-ComfyUi-Timeline-Node module for custom nodes: [Errno 2] No such file or directory: 'E:\\workplace\\ComfyUI\\custom_nodes\\TimeUi-a-ComfyUi-Timeline-Node\\__init__.py'

**Comment by corbin-hayden13** [comment]
For now, you have to clone the repository and take `TimeUI-Node` out of `TimeUI-a-ComfyUI-Timeline-Node` and put `TimeUI-Node` into your `custom_nodes` folder becuase that's the folder with `__init__.py`.  A restructuring of the repository is coming soon.

**Comment by corbin-hayden13** [comment]
This has been patched with #10
